### ISSUE TITLE
Deployment Guide

### ISSUE THREAD

**Issue by NilsFrkal** [apigee/consumer-data-standards-au#12]
Hi, 

Is there a deployment/prerequisite guide available for this? 

Do we need to setup a GCP account and enable Apigee (as per https://apigee.google.com/setup) and would this work with the evaluation option and how/where do we need to set up the mentioned pre-requisites (nodejs etc.)? Or is this meant to be installed on prem in combination with Apigee microedge?

Thank you very much.

Best, Nils

**Comment by deboraelkin2** [comment]
Hi Niels, this reference implementation works on Apigee Edge (or with minor modifications, with Apigee for Private Cloud).
Unfortunately, Apigee free trials are no longer provisioned on Edge, but on Apigee X, the newest release of Apigee.
We are working to produce a version of the reference implementation that works in Apigee X.

**Comment by NilsFrkal** [comment]
Thanks a lot for the clarification. Best, Nils
